version: "2.1"

services:
  authentication-server:
    image: master-thesis/authentication-server:lastest
    ports:
      - "9090:9090"
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - security
      - baseinfrastructure_memcache
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging
  zipkin:
    image: master-thesis/zipkin-server:lastest
    ports:
      - "8050:8050"
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging

  turbine-stream:
    image: master-thesis/turbine-stream-server:lastest
    ports:
      - "7070:7070"
      - "7071:7071"
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging

  spring-boot-admin:
    image: master-thesis/spring-boot-admin-server:lastest
    ports:
      - "8000:8000"
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery

  api-gateway:
    image: master-thesis/api-gateway-server:lastest
    ports:
      - "5050:5050"
    environment:
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_memcache
      - baseinfrastructure_messaging

networks:
  security:
    driver: bridge
  baseinfrastructure_memcache:
    external: true
  basecloudnativeinfrastructure_discovery:
    external: true
  baseinfrastructure_messaging:
    external: true