version: "2.1"

services:
  zipkin:
    image: master-thesis/zipkin-server:lastest
    ports:
      - "4000:4000"
    environment:
      - server.port=4000
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_messaging

  spring-boot-admin:
    image: master-thesis/spring-boot-admin-server:lastest
    ports:
      - "8000:8000"
    environment:
      - server.port=8000
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery

  api-gateway:
    image: master-thesis/api-gateway-server:lastest
    ports:
      - "5050:5050"
    environment:
      - server.port=5050
      - spring.profiles.active=docker
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - basecloudnativeinfrastructure_discovery
      - baseinfrastructure_memcache
      - baseinfrastructure_messaging

networks:
  baseinfrastructure_memcache:
    external: true
  basecloudnativeinfrastructure_discovery:
    external: true
  baseinfrastructure_messaging:
    external: true