
server:
  use-forward-headers: true

security:
  sessions: ALWAYS
  oauth2:
    client:
     clientId: my-trusted-client
     clientSecret:
     accessTokenUri: http://localhost:3030/oauth/token
     userAuthorizationUri: http://localhost:3030/oauth/authorize
     auto-approve-scopes: '.*'
     registered-redirect-uri: http://localhost:3030/login
    resource:
     preferTokenInfo: false
     id: oauth2-resource
     user-info-uri: http://localhost:3030/userInfo.json
    sso:
      login-path: http://localhost:3030/login

proxy:
  auth:
    routes:
      account-management-web-site: oauth2
    load-balanced: true

zuul:
  retryable: true
  ignoredServices: '*'
  sensitiveHeaders:
  strip-prefix: false
  add-host-header: true
  add-proxy-headers: true
  ignore-security-headers: false
  routes:
    guest-web-site: /guest/**
    goods-management-web-site: /goods-management/**
    account-management-web-site: /account-management/**
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: account-service


management:
  security:
    enabled: false