version: "2.1"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - "/data/db:/data/db"

  database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "/home/vvaudi/Desktop/microservices-master-thesis/datastore/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
