spring:
  application:
    name: purchase-order-service
  data:
    cassandra:
      keyspace-name: purchaseOrderEventKeyspace

security:
  basic:
    enabled: false
  oauth2:
    client:
     clientId: my-trusted-client
     clientSecret:
     accessTokenUri: http://localhost:9090/oauth/access_token
     userAuthorizationUri: http://localhost:9090/oauth/authorize
     clientAuthenticationScheme: form
    resource:
     userInfoUri: http://localhost:9090/account/userInfo
     preferTokenInfo: false
